const DATA={
    sections: [
        {
  
          id: 1,
          name: 'Brown Brim',
          imageUrl: 'https://i.ibb.co/nQ84F0Y/11.jpg',
          title: "Rock climbing: from ancient practice to Olympic sport",
          summary:`Since modern recreational climbing began in the late 19th century, breakthroughs derived from new technology and tactics have pushed it in myriad directions.
                  Today, as international competitors at the highest echelons of the sport look forward to climbing’s debut in the 2020 Tokyo Olympics, thousands of new enthusiasts have been introduced to the sport thanks to the burgeoning indoor climbing gym industry. Meanwhile, ever growing numbers of elite climber-explorers continue to travel to the far ends of the earth in search of untouched stone.
                  To understand what everyone is really up to, it helps to get a grip on the history of climbing and the language that has evolved around it.
                  An ancient activity`,
          text:`
                Alaska Wilderness Project Seeks to Rejuvenate Alaskan Exploration
                Alaska is considered one of the last places in the United States that is truly wild, one of the last places with opportunities to experience exploration in a genuine sense. Its land mass is larger than Texas, California, and Montana combined, yet barely more than 700,000 people reside there. In between the faint sketches of civilization lies an inconceivable expanse of wilderness, much of which is accented by mountain ranges. Alaska is a treasure trove of unclimbed peaks, yet the majority of the climbing there takes place in Denali National Park—Denali itself sees more than 1,000 attempts annually. The Alaska Wilderness Project (AWP), a nonprofit launched by climbers Benjamin Lieber and Alex Hansen, seeks to inspire exploration into the lesser known regions.
                Lieber and Hansen had been climbing together in Alaska for the last several years, always following the crowds to Denali National Park. This season, however, Denali was closed to climbers due to the pandemic, so the pair had to forge a new plan. They found a bush pilot willing to fly them into the Hayes Range—an area that the duo previously could not have pointed out on a map—and made the journey out.
                “We went on this trip and the mountain range was unbelievable,” Lieber said. “So we just started thinking more about how much is left out here while we still spend all our time in Denali. Denali is awesome, but Alaska is ginormous and that is just one small area.”
                “We’re trying to contribute more instead of just going on expeditions for ourselves,” Lieber said. “At the very least we could inspire a couple people to take their efforts to another range. Even for people like my parents—they’re not going mountaineering in Alaska—but they will happily read about the history.”
                The four pillars of the AWP are: preservation, history, exploration, and empowerment. Promoting preservation and conservation of these wild places; piecing together a comprehensive and accessible history of people’s relationship to the mountains in Alaska; pushing the limits of exploration further; and empowering and inspiring others to step into the unknown.
                The AWP was just launched this year and is still in its infancy, but the team plans to bring these pillars to fruition via a multimedia experience of the Alaskan wilderness: the written word, photographs, a video series, trip-tips, a podcast, coffee table books, etc. With a background in art and design, Lieber is fit for the undertaking. The project is partnered with companies such as Sterling, Rab, La Sportiva, and more.
                Preservation
                Through bringing awareness to the rich history and majesty of the Alaskan wilderness, the project hopes to work in conjunction with state-specific organizations already fighting for protection of these wild spaces.
                “Our aim is to both add to the conversations already being had and to start new projects that further the discussion of these topics, add a new light, or open new conversations entirely,” co-founder Alex Hansen said. “Furthermore, we want to make sure what resources we can provide in the short-term aren't redundant and are actually effective. For us, that means utilizing our strengths in historical-storytelling (and storytelling in general) to inform our audience of important historical, contextual information regarding the land and the policies that drive and have driven its current state to date.”
                History
                Much of the history and documentation of the mountains in Alaska is found in the pages of old books and maps, and not readily accessible unless you go looking for it. The AWP's goal is to create a modern way of presenting this information that is easily accessible to anyone with a computer or cell phone, through online documentation, photographs, videos, etc.
                “The idea is to do this holistic historical review of Alaskan mountain ranges, and to go out and have a modern take on exploration,” Lieber said. “We will try to continue to explore in some of these places that are still relatively unexplored.”
                From digging through the archives of old mountaineering literature, surveying the land, and following in the footsteps of early explorers, the AWP will create a multimedia experience of the history of exploration in Alaska.
                
                Exploration
                The beating heart of climbing has always been exploration. The beckoning of the unknown was the impetus for our predecessors to ever step foot on a mountain. Today, climbing has evolved into so many things for so many people: some folks are into hard bouldering, others like to stay fit at the rock gym, some enjoy the social scene of a crag day. Yet all of this is derived from that sense of exploration, which the AWP strives to reignite.
                “There is this common perception in climbing that the big mountains are all tracked out,” Lieber said. “That is way far from the truth.”
               `
        },
        {
          id: 2,
          name: 'Blue Beanie',
          summary:`A week-long gathering in Scotland of mountaineers from across the world has been hailed a massive success as climbers from 22 countries enjoy Scotland’s mountains.
          Climbers from Europe, Scandinavia, the Middle East, the Americas and South Korea came as guests of Mountaineering Scotland to pair up with UK climbers and sample the unique character of Scottish winter climbing.`,
          imageUrl: 'https://i.ibb.co/Gc2bNkF/grand-teton-north-buttress-direct-6.jpg',
          title: `Scottish snow and ice an international hit`,
          text:`A week-long gathering in Scotland of mountaineers from across the world has been hailed a massive success as climbers from 22 countries enjoy Scotland’s mountains.
                Climbers from Europe, Scandinavia, the Middle East, the Americas and South Korea came as guests of Mountaineering Scotland to pair up with UK climbers and sample the unique character of Scottish winter climbing.
                Ice-axe wielding and crampon-shod, they climbed well-known classic ice routes and hard, modern test-pieces – and also notched up six entirely new routes, including one amongst the hardest ever done in Scotland.
                Some of the 60-strong group even took part in a mountain rescue, when they witnessed an avalanche on Ben Nevis and abandoned their own climbs to give initial support and First Aid to the victim until the Mountain Rescue Team arrived for the evacuation.
                After a week of climbing, sometimes in challenging weather, both guest and host climbers were unanimous in declaring the event a great success, with the guests, most of whom have experience of climbing in the Alps and greater ranges – enthusing about the whole challenge and experience of winter climbing in Scotland.
                Stuart Younie, CEO of Mountaineering Scotland, said “Mountaineering Scotland has been delighted to host this event in our 50th year, and to be able to welcome climbers from 22 different countries and all over the UK to enjoy some of the best winter climbing conditions Scotland has seen in many years. It’s been a great opportunity to showcase Scotland on an international stage and many of our international guests have been so enthused about the experience they are already talking about when they are going to come back. Thanks to our partner organisations and to all the volunteers who helped deliver such a fantastic event.”
                Streap Alba Geamhradh 2020 – the name means Climb Scotland Winter 2020 in Gaelic – was revived this year as part of the celebrations to mark Mountaineering Scotland’s 50th anniversary. It was supported by the Scottish Mountaineering Club, The Alpine Club, British Mountaineering Council and Salewa.
                Organisers had been worried that climbing conditions would be poor, with a relatively warm December and January, but in the week or so before the international guests arrived colder conditions blew in and plastered the cliffs and gullies with snow and ice.
                The visiting climbers were teamed up with UK climbers of similar ability and climbed in various mountain areas of Scotland, staying in climbing huts in the Cairngorms, Glen Coe and on Ben Nevis itself.
          `
        },
        {
          id: 3,
          name: 'Brown Cowboy',
          summary:`The winners of the Nick Estcourt Award 2020 have been announced. The award was established to commemorate the climbing achievements of Nick Estcourt, and to encourage future generations of expedition mountaineers. After 40 years, this will be the final year that the grant will be awarded in its current format.
          The winners of the 2020 Nick Estcourt Award are Tom Livingstone and Luka Strazar who, Covid-19 restrictions permitting...`,
          imageUrl: 'https://i.ibb.co/933Q3bH/MTc4-OTEw-Mz-Qy-OTgw-NTc2-Nzc1.webp',
          title: `Tom Livingstone and Luka Strazar announced as winners of the final Nick Estcourt Award`,
          text:`The winners of the Nick Estcourt Award 2020 have been announced. The award was established to commemorate the climbing achievements of Nick Estcourt, and to encourage future generations of expedition mountaineers. After 40 years, this will be the final year that the grant will be awarded in its current format.
          The winners of the 2020 Nick Estcourt Award are Tom Livingstone and Luka Strazar who, Covid-19 restrictions permitting, will attempt a new line on the spectacular north face of Jannu (7,710m) in Nepal this post-monsoon season. In line with the spirit of the award the climbers will accept the true challenge of their objective by climbing Alpine Style and not carrying bolts.
          Their bold, intended climb captured the imagination of the Trustees such that they decided to end their administration of the award with a higher than usual grant of £2,500.
          Tom and Luka made the first ascent from the north of Latok I (7,145m) with Aleš Česen in 2018 in a seven-day round-trip from basecamp. This trip was part-funded by a BMC expedition grant and received the highest grade award, the Piolet d'Or.
          Nick Estcourt died on K2 in 1978 and since 1980 the Nick Estcourt Award has kept his name alive by awarding an annual grant to mountaineering expeditions tackling objectives of the kind that Nick loved.
          The trustees are proud to have kept the award going for 40 years but have decided that this will be the final year in which the grant will be awarded in its current format. The remaining funds will now be made available to the Mount Everest Foundation who will continue to keep Nick’s name alive by attaching his name to a single expedition each year which fulfills the criteria of the Nick Estcourt Award.
          `
        },
        {
          id: 4,
          name: 'Grey Brim',
          summary:`August 14, 2020: We are bivying on the Teton Glacier below the North Face of the Grand. Above us are the same stars the Shoshone and other Indigenous people have gazed upon for centuries, long before the arrival of explorers and settlers. The air is calm but cold. Mark Jenkins, who has forgotten his sleeping bag, places his legs into his 50-liter backpack, stuffing our extra clothes around his feet for insulation. He wears my black puffy and wraps his own around his legs. We both lie miserably on the ice, waiting for our 4 a.m. alarm.
          To most of us, sleeping before a big climb is a myth, only executed properly by the most experienced....`,
          imageUrl: 'https://i.ibb.co/4VSpHJj/grand-teton-north-buttress-direct-1.jpg',
          title: `Finding a new route on the Grand Teton: the North Buttress Direct (5.10+ R)`,
          text:`
          August 14, 2020: We are bivying on the Teton Glacier below the North Face of the Grand. Above us are the same stars the Shoshone and other Indigenous people have gazed upon for centuries, long before the arrival of explorers and settlers. The air is calm but cold. Mark Jenkins, who has forgotten his sleeping bag, places his legs into his 50-liter backpack, stuffing our extra clothes around his feet for insulation. He wears my black puffy and wraps his own around his legs. We both lie miserably on the ice, waiting for our 4 a.m. alarm.
          To most of us, sleeping before a big climb is a myth, only executed properly by the most experienced. From my snug sleeping bag, I hear Mark snore from time to time in between shivering. When the alarm sounds, my senses are somewhere between a deep state of hallucination and consciousness. I wake to the cold, dark air and remember where I am. Jitters of excitement stir me to action, but soon enough I make a conscious effort to set those emotions aside and focus on immediate tasks.
          THREE YEARS AGO, while training in a gym in Jackson Hole for an upcoming expedition to Kyrgyzstan, I often walked down the hallway to examine a photo of a climber atop Teewinot. Just behind him rose the Grand Teton's magnificent North Face. I began to notice a distinct buttress on the face: a lone, tall pillar of what looked like clean granite. My ardor for this proud feature led me to consult Leigh Ortenburger and Reynold "Renny" Jackson's guidebook, A Climber's Guide to the Teton Range. Encyclopedic in breadth and depth, this guidebook contains all the known routes and their intriguing stories. To my delight, I discovered that my magnificent 2,000-foot buttress was unmentioned. I began to dream.
          The Grand Teton was purportedly first climbed by the Hayden Geological Survey during a cold July in 1872. The explorers presented an enigmatic route description up the mountain's west face, but the snow and features they told of don't seem to match up with the actual terrain, which has cast doubt on their ascent. They seemed to take more interest in the rock structure atop the Enclosure, a subpeak on the west spur of the Grand Teton. The summit of the Enclosure was used by Shoshone Native Americans as a place for spiritual purposes. Evidence of prior humans on the Enclosure suggests that the Grand Teton may have been climbed well before white people arrived.
          Two decades after the Hayden expedition, William Owen, a man obsessed with being the first at any endeavor, showed up in Wyoming. After eight years of failed attempts, he found the key to the summit in 1898 with Franklin Spalding. Owen claimed the first ascent of the mountain, via what is now known as the Owen-Spalding or OS route. This was the beginning of a century of controversy over who the mountain's first ascensionists really were.
          
          Mark and I kick our aluminum crampons into the steep neve of the Teton Glacier. The beams of our headlamps sweep right and then left. We're searching for a snow bridge across the plunging bergschrund. Our opportunity appears at the top of a funnel where a large chunk of snow has fallen from a hanging block directly above our heads. Mark crosses the bridge first, switches from crampons and approach shoes to rock shoes, and sets out. We simulclimb five pitches of fourth- and easy fifth-class along an exposed, west-trending ledge. We have to down climb in several places and make one precarious rappel with our rope wrapped around a shallow undulation in the rock. We're moving swiftly, but our approach has taken over an hour longer than we anticipated.
          At the base of the climb, I rack and head up the first pitch of the unknown. It's my first rodeo on a new route, but not Mark's. He has racked up miles of new terrain.
          Mark is a Laramie, Wyoming local. He first started climbing in high school when his PE teacher brought the class out to Vedauwoo, an outcropping of granite known for its stout grades, flared offwidths and blood-letting ability. Mark's first big expedition was a failed attempt on Denali. As a hungry alpinist and professional writer, he began applying for spots on international expeditions. His first Himalayan summit was 8027-meter Shishapangma, in Tibet. This successful ascent in 1984 led him to a life of climbing big new routes all over the world. He also managed to slip in the first crossing of Siberia by bicycle (7,500 miles), the first descent of the Niger River in West Africa, and the first descent of Hang Son Doong, the largest cave in the world, located in central Vietnam. Suffice it to say that Mark has considerable experience being the first to do something. When I started climbing with him this past spring, I knew immediately he was the partner I needed to get up the 2,000-foot north buttress of the Grand Teton. His eyes lit up when I told him about my dream.
          
          Mark and I find the first two pitches of the North Buttress Direct to be stellar climbing, following 5.9 hand cracks that tapered down to 5.10 fingers. For a moment, I think we've hit the jackpot, a future classic composed of solid rock and beautiful climbing. Then I start leading the third pitch. A perfect fist crack transmogrifies into scary, dirty, hard-to-protect face climbing. (This pitch will turn out to be the crux of the route, 5.10+ R.) My bones are shivering with fear after finishing the pitch. Luckily, the next three pitches provide us with enjoyable, if sometimes loose, moderate climbing.
          On the top of Pitch 6, water is running down the rock to our left, fed by a melting snowfield. The closest established route ascends this snow gully. We fill our bottles and simulclimb the next three pitches of easy fifth-class. The buttress again rears up before us and we dispatch a steeping 5.7 corner, followed by an awkward 5.9 roof. Here we take a break in a notch of the buttress, eat a little, drink a lot and briefly allow ourselves to be satisfied by our speed and efficiency thus far.
          After no more than five minutes of rest, we begin the last third of the climb: the final tower of the northeast buttress before it connects to the East Ridge high the mountain. I climb up loose "ghost flakes," 400-pound slabs of rock ready to rip off at any moment. It's only 5.7, but Mark is below me in the line of fire. I attempt to link this pitch with the next, climbing a right-facing corner, traveling over more ghost flakes. The remaining gear on my harness is dwindling. I have limited options on what to place in the rock, so I run it out before building an anchor right below a large roof. Mark takes the lead up through this short but frustrating 5.9 overhang. The lip of the roof forms a pronounced bottleneck but he can't fit into the gap with his pack on (ice axe, crampons, puffy, etc.), so he leaves it hanging and easily clears the problem. He hauls up both packs before I climb this awkward corner. Now past the last difficulties, we return to simulclimbing.
          
          `
        },
        {
          id: 5,
          name: 'Green Beanie',
          summary:`Since the 10-person team of Nepali climbers completed the first winter ascent of K2 (8611m) on January 16, there have been two confirmed deaths and three climbers—Juan Pablo Mohr Prieto (Chile), Muhammad Ali Sadpara (Pakistan) and John Snorri Sigurjonsson (Iceland)—have been missing since February 5, when they were last seen near the Bottleneck at approximately 8200 meters. They are presumed dead. So far there have been multiple helicopter searches while search teams on foot have been halted by adverse weather.
          Sajid Ali Sadpara, Muhammad's 22-year-old son, was with his father and Snorri Sigurjonsson and Mohr Prieto when they left Camp 3 (ca. 7300m) on February 4 to make a summit push during a narrow break in a pattern of cold, turbulent weather...`,
          imageUrl: 'https://i.ibb.co/s1HhQhR/k2-abruzzi-spur-wiki-photo-bw.jpg',
          title: `JP Mohr Prieto, Muhammad Ali Sadpara and John Snorri are missing, presumed dead on K2          `,
          text:`Since the 10-person team of Nepali climbers completed the first winter ascent of K2 (8611m) on January 16, there have been two confirmed deaths and three climbers—Juan Pablo Mohr Prieto (Chile), Muhammad Ali Sadpara (Pakistan) and John Snorri Sigurjonsson (Iceland)—have been missing since February 5, when they were last seen near the Bottleneck at approximately 8200 meters. They are presumed dead. So far there have been multiple helicopter searches while search teams on foot have been halted by adverse weather.
          Sajid Ali Sadpara, Muhammad's 22-year-old son, was with his father and Snorri Sigurjonsson and Mohr Prieto when they left Camp 3 (ca. 7300m) on February 4 to make a summit push during a narrow break in a pattern of cold, turbulent weather. Sajid turned around at the Bottleneck because he wasn't feeling well and was having problems with the regulator on his bottled oxygen. He waited at Camp 3 for their return, but with more high winds in the forecast and with his oxygen supply running out, he descended to Base Camp after a brief search in the vicinity of Camp 3.
          A February 5 post on Snorri's Facebook page reads: "Dear friends, we regret to inform that we have not received any new news from John, Ali, and Pablo after the night. The only news we have is that Sajid Ali is descending safe from Camp 3. We are grateful to the Pakistani army that has activated a helicopter rescue team and the Icelandic ministry of foreign affairs for their great cooperation. Thanks for all your support, we keep faith."
          On February 9, Seven Summit Treks Director Chhang Dawa Sherpa announced on Instagram that the company was leaving Base Camp, ending their expedition. Some of the expedition staff is remaining behind to support the climbers who plan to continue searching when the weather allows.
          Muhammad Ali Sadpara was among the most experienced winter mountaineers on the mountain, having completed the first winter ascent of Nanga Parbat with Simone Moro and Alex Txikon in 2016. In a February 8 article for Rock and Ice, Arnette reported that Sadpara had recently gained sponsorship from the Pakistan government after proving himself so many times on the big mountains.
          Arnette reported that Mohr Prieto had climbed five 8000-meter peaks without bottled oxygen: Annapurna, Manaslu, Everest, Lhotse and Dhaulagiri. Snorri Sigurjonsson was on his third K2 expedition; this was his second winter attempt, having climbed it on his first attempt in summer. He has also climbed Lhotse, Broad Peak and Manaslu.
          On February 5, the same day those men where last seen heading for K2's summit, Bulgarian climber Atanas Skatov (Bulgaria) died when he fell while descending from Camp 3. Planet Mountain reported Chhang Dawa Sherpa saying that it appears the accident happened while Skatov was transitioning from one fixed rope to another. His body was recovered later that day.
          Dawa Sherpa's Instagram post on February 5 reads in part, "Atanas, a good friend of [mine], who climbed 10 x 8000m peak. [He] was...very appreciated...by all other members of the expedition. Deep condolences for his family and friends. We lost [a] great mountain friend today."
          The first death on K2 this winter happened low on the mountain on January 16, the same day the 10-man team summited, when Sergi Mingote (Spain) fell while descending from Camp 1. Dawa Sherpa posted on Instagram that Alex Gavan (Romania), Tamara Lunger (Italy) and two other unnamed Polish climbers in Advance Base Camp were the first to reach Mingote, but he soon died of his injuries. Planet Mountain reported: "The expert Catalan had climbed seven 8000ers without supplementary oxygen at a mind-boggling speed: Broad Peak, K2 and Manaslu in 2018, Lhotse, Nanga Parbat, Gasherbrum II and Dhaulagiri in 2019, as well as Everest from Tibet in 2001 and from Nepal in 2003."
          `
        },
        {
          id: 6,
          name: 'Palm Tree Cap',
          imageUrl: 'https://i.ibb.co/RSD2zkC/k2-winter-alex-gavan-2.jpg',
          summary:` The four groups include the large commercial operation of Seven Summit Treks (SST), a Nepali company founded by six brothers, two of whom have climbed all 14 8000-meter peaks; the three-person, Nepali/Sherpa team of Mingma Gyalje Sherpa ("Mingma G"), Dawa Tenzin Sherpa and Kili Pemba Sherpa; Nirmal "Nims" Purja's group that includes six Nepali/Sherpa climbers in support; and another three-person team that consists of John Snorri Sigurjonsson (Iceland) with Muhammad Ali Sadpara and his son Sajid (Pakistan).
          The Seven Summits Treks expedition consists of 22 clients and 27 staff members...`,
          title: `Four expeditions are attempting the first winter ascent of K2: Alex Gavan discusses current efforts`,
          text:`UPDATE, January 16:A team of 10 Nepali/Sherpa climbers from separate expeditions climbed the final meters to the summit together as one group at 5 p.m., completing K2's first winter ascent. You can find our story about that here.
          UPDATE, January 15: Alan Arnette reports that a new all-time winter high point has been attained—7800 meters—by Mingma Gyalje Sherpa and Seven Summit Treks leaders Mingma David Sherpa, Mingma Tenzi Sherpa and Sona Sherpa. They have reached Camp 4 and hope to stand on the summit within the next 24 hours.
          There are currently four expeditions laboring for the first winter ascent of K2 (8611m), which is the last 8000-meter peak yet to be climbed in the coldest, harshest season. The efforts between the four groups are in part both collective and separate. As of January 12, ropes have been fixed to Camp 3, just above 7300 meters, but that camp has yet to be fully established and recent high winds have destroyed and scattered gear at the lower camps.
          
          The four groups include the large commercial operation of Seven Summit Treks (SST), a Nepali company founded by six brothers, two of whom have climbed all 14 8000-meter peaks; the three-person, Nepali/Sherpa team of Mingma Gyalje Sherpa ("Mingma G"), Dawa Tenzin Sherpa and Kili Pemba Sherpa; Nirmal "Nims" Purja's group that includes six Nepali/Sherpa climbers in support; and another three-person team that consists of John Snorri Sigurjonsson (Iceland) with Muhammad Ali Sadpara and his son Sajid (Pakistan).
          The Seven Summits Treks expedition consists of 22 clients and 27 staff members. Not surprisingly, SST's ambition to guide people on a winter ascent that has yet to be accomplished by the best climbers in the world has brought plenty of controversy. Professional climbers Alex Gavan (Romania) and Tamara Lunger (Italy) are counted as members of the SST expedition, but Gavan told Alpinist that he and Lunger are only affiliated with the group for logistical support.
          "We are sharing the base camp logistics with one other expedition for efficiency reasons but other than that we have our own climbing strategy and acclimatization schedule, our own decision making on and off the mountain and even our own base-camp dining tent," Gavan wrote in an email.
          Gavan offered an interview to Alpinist to give readers his perspective on how things are going on the mountain. This is Gavan's first winter attempt on an 8000-meter peak and his first time on K2, but he has climbed seven other 8000ers without bottled oxygen, achieving first, second and third Romanian ascents of those peaks in the process. Lunger, meanwhile, has already climbed K2 without bottled oxygen, via the Abruzzi Spur in 2014. In 2016 she came within 70 meters of joining Ali Sadpara, Simone Moro (Italy) and Alex Txikon (Spain) on the summit of Nanga Parbat (8125m) for the first winter ascent of that peak. She has other winter expedition experience as well, including a winter attempt on Manaslu (8163m) with Moro in 2015.
          
          Gavan's most recent update from January 11:
          The new forecast we got shows a good weather window over the next couple of days. Due to the usual unstable K2 winter weather, any reasonable fair weather window must be used at the maximum. So after thoughtful consideration, Tamara and myself decided to further our acclimatization and make another equipment deposit at altitude. The plan is to climb to Camp 1 on January 13. If the wind is too high, we will also spend the next day there. If not, we will establish Camp 2 and on January 15, climb over the Black Pyramid, set Camp 3 at around 7300 meters and spend another acclimatization night there. By January 16, we need to be back at Base Camp, because [on January 17 the wind is forecasted] to be more than 80 kilometers per hour (kph) at 6000 meters.
          Over the last couple of days all tents from Camp 2 were destroyed by the high winds, and many climbers lost also essential equipment. Our stuff in Camp 1 is still there since we took down the tent and packed it together with the equipment inside and secured it to the rocks.
          Are all expeditions still focused on the Abruzzi?
          This year all climbers are focused on the Abruzzi Spur, the original line of the mountain's first ascent in 1954.... The lessons taken from [previous winter attempts point to] the Abruzzi as the...the most probable route to follow for reaching a first winter summit of the K2. To date, the highest point reached during winter [is about] 7650m.
          What is your high point so far? Do you know how the other expeditions are faring?
          We were the last team to arrive at the base camp at 4970m, on the Godwin-Austen Glacier. The first to arrive were the teams of John Snorri, Ali Sadpara (who was part of the first winter summit team on Nanga Parbat in 2016), and [Sadpara's] son Sajid on December 5, then Mingma G's team on December 18 and Nirmal Purja on December 25.
          In their first night at base camp, Snorri's kitchen tent was blown up by the strong wind, and one of the staff was totally bathed by a full bowl of water while immersed in his sleeping bag.
          [As of January 7], the highest point reached [this season] is the lower Camp 3 at about 7300 meters, above the Black Pyramid. The route finding on the glacier from Base Camp to the Advanced Base Camp and then the rope fixing to Camp 1 was entirely done by Snorri's team; then the rope fixing from Camp 1 to Camp 2 has been made by Mingma G's team. And from Camp 2 to lower Camp 3 the line fixing was a combined effort by the teams of Mingma G and Nirmal [Purja].
          Since Tamara and I arrived, we spent four nights in base camp for proper acclimatization then we took advantage of the only fairly good weather window, and on January 2, we climbed up to [the] Japanese Camp at about 5750 meters, where we stopped for the night, since the small spot of Camp 1 at 6070 meters can only accommodate six or seven tents, maximum, and this extremely small real estate was already booked for the evening. On January 3 we reached Camp 1 [and by then] the weather had completely changed from what the forecast predicted. The wind was picking up fast, and we decided to retreat to base camp the next day, postponing our climb to Camp 2 as initially intended. It proved to be the right decision. The climbing conditions [improved after that, as the wind scoured] the face completely dry. [There was] zero risk of avalanches and just perfect, firm snow and beautiful ice to climb on. My heart was full of joy climbing with just my two ice axes, not tethered to anything, but then I clipped a carabiner onto the fixed ropes after I saw some falling rocks, and then later I used an ascender for added safety.
          One word about the route fixing: It is quite customary in Himalayan climbing, although not necessarily wise, to use old ropes or anchors from previous expeditions where it is possible to do so. Such it is the case with the current K2 winter season. Some of the ropes are indeed new, but significant portions of them are not. On December 4, midway to Camp 1, one of these old ropes snapped and it is truly remarkable that no one died.
          
          `
        },
        {
          id: 7,
          name: 'Red Beanie',
          imageUrl: 'https://i.ibb.co/BLW7QjN/Alex-Honnold-free-solo-climbs-El-Capitan-s-Freerider-in-Yosemite-National-Park-National-Geographic-J.jpg',
          summary:`Tommy Caldwell and Alex Honnold have completed another linkup of staggering proportions that left them both "hobbling around," as Honnold recently told Alpinist.
          But this time, instead of Yosemite or Patagonia (where the two have made headlines numerous times in the past) it was in Rocky Mountain National Park...`,
          title: ` Alex Honnold and Tommy Caldwell complete "Continental Divide Ultimate Linkup" in Rocky Mountain National Park`,
          text:`Tommy Caldwell and Alex Honnold have completed another linkup of staggering proportions that left them both "hobbling around," as Honnold recently told Alpinist.
          But this time, instead of Yosemite or Patagonia (where the two have made headlines numerous times in the past) it was in Rocky Mountain National Park, Colorado, near Caldwell's home in Estes Park—a place where he grew up climbing with his dad.
          They dubbed their route the Continental Divide Ultimate Linkup (CDUL, "pronounced 'cuddle' for how we warmed up in the middle of the night," Caldwell wrote on Instagram). They stood atop 17 summits that included 11 technical climbing routes (approximately 65 pitches of 5.6 to 5.11), covering about 35 miles and 20,000 feet of vertical gain in roughly 36.5 hours.
          They left the Longs Peak Ranger Station around 5:15 a.m. on Friday, July 17, and finished at Bear Lake at 5:40 p.m. Saturday, July 18. Honnold said they simulclimbed nearly all their roped pitches and scrambled the rest, including the Sharkstooth (5.6) and the Central Ramp (5.8) on Mt. Alice.
          "In some places it was better to free solo and leave our packs at the base," Honnold told Alpinist. Of course, for the pair that set the speed record on the Nose of El Capitan (1 hour, 58 minutes, 7 seconds) in 2018, and for Honnold, who free soloed El Cap's Freerider (5.12d/13a, 3,000') in 2017, their ropeless climbing on the CDUL traverse was well within their comfort zone.
          
          "We're both slightly injured," Honnold told Alpinist over the phone on July 21. He was resting at Caldwell's house and had been playing board games with Caldwell's children. Honnold said he slipped and bruised his hip, and that Caldwell had a sore Achilles tendon.
          "I'm not from here, so this terrain is pretty new to me," Honnold said. When jokingly asked how Rocky Mountain National Park compares to Patagonia, he replied, "It actually does have a similar vibe to Patagonia because it has surprisingly complicated terrain. The places are different in terms of scale, of course, but one of the cruxes [for the CDUL] was the constant decision-making. We were only on a trail for the start and finish."
          "Huge thanks to Maury Birdwell and Adam Stack for supporting us during the journey with key resupplies," Honnold wrote on Instagram July 20.
          Adding to their challenge was that they missed a resupply. Caldwell wrote in a July 21 Instagram post:
          I guess my wish for a character-building experience paid off. From a runner's perspective, we made some rookie mistakes. We missed our pre-night support drop-off and therefore ended up climbing through the night in our short shorts [amid] howling winds at 13,000 feet [with a] phone jammed under my hat as a flashlight. [We were] calorie deprived until our hero [Adam Stack] rescued us with food and headlamps. By mid-morning I was throwing up. [Alex] of course was steady and high-spirited as always....
          
          99.9% of people would have given up when they did not have a headlamp or food for part of the night. The quote of the night [from Alex]: "Soloing by iPhone is not that sweet." Proud of [them] for an epic effort and setting a new bar for what is possible when you combine ultra running and climbing.
          Caldwell had been preparing for the big day for some time with Stack as a partner. Honnold said Caldwell invited him to go for the linkup about two weeks beforehand.`
        },
        {
          id: 8,
          name: 'boot',
          imageUrl: 'https://i.ibb.co/MG9BS6w/1.jpg',
          summary:`As anyone who has had a severe foot injury can attest, shoes just don't fit the same after you get permanent hardware drilled into your bones. Even prior to my Lisfranc fracture, which resulted in three long pins in my left foot, I fetishized footwear—an obsession that peaked in my fashion days and likely began when I was a ballet dancer. People close to me would say that I am still crippled by this footwear fixation, aka "neurotic tootsie syndrome." I am also a smaller size, and in the mountain boot category, my options are most often limited to the "women's versions," which has given me and other women a slight chip on our shoulders. When us smaller-footed climbers got the consolation prize of the Scarpa Ribelle HD, I had to try it.
          ...`,
          title: `Scarpa Ribelle HD: Boots that can keep up in the mountains`,
          text:`As anyone who has had a severe foot injury can attest, shoes just don't fit the same after you get permanent hardware drilled into your bones. Even prior to my Lisfranc fracture, which resulted in three long pins in my left foot, I fetishized footwear—an obsession that peaked in my fashion days and likely began when I was a ballet dancer. People close to me would say that I am still crippled by this footwear fixation, aka "neurotic tootsie syndrome." I am also a smaller size, and in the mountain boot category, my options are most often limited to the "women's versions," which has given me and other women a slight chip on our shoulders. When us smaller-footed climbers got the consolation prize of the Scarpa Ribelle HD, I had to try it.
          In order to fully appreciate the Ribelle HD, it helps to have an understanding of Scarpa Ribelle OD, which is the HD's older sibling. The great alpinist Ueli Steck helped design the Ribelle OD and it was a revolutionary mountain boot. With a nimble, upturned sole that is akin to the rocker of a running shoe, it is also stiff, crampon compatible and comfortable. The Ribelle OD is also equipped with a gaiter that keeps out snow while allowing for more natural ankle movement. It is as if an approach shoe, a trail running shoe and a mountain boot had a child. The Ribelle HD is a more traditional mountain boot—with the Ribelle OD's exact same smear-happy, upturned sole, only coupled with a leather upper instead of the OD's low-cut synthetic upper and built-in gaiter.
          
          A pair of women's size 38 Ribelle HD boots weighs less than 3 pounds. Scarpa describes it as a boot that can be "light and fast in the alpine, and also cross over to function as a heavy-duty backpacking boot," which is funny because the Ribelle HD is a tad bit lighter than most basic "backpacking boots." Although the HD has a rather unique sole, I get why they would compare the HDs to more classic leather backpacking or hiking boots, because the rest of the boot does give off a "basic boot" vibe—at least that was my first impression.
          After picking up the boot and trying them on, however, they definitely are not a basic boot. They felt great, especially for me as someone who fits Scarpa well; I found instant comfort. When I went to lace them, I noticed that closed grommets stopped at the ankle, changing to open hooks. This is a super big pet peeve of mine, yet the hooks seem to be angled down enough to keep the laces in and not get caught on the other boots' laces.
          I am typically a 37 or 37.5 in Scarpa footwear, but in their leather Crux, I size down to a 36.5 and I recently gave away a pair of Charmoz in a size 37, that just were a bit too small. I knew that likely the Ribelle HDs would give a little over time as the leather broke in and stretched, so I was hesitant to get the 37.5. I also couldn't try on the 37 because there didn't seem to be any pairs in Canada. But after wearing the 37.5 size I think they are the right size for me after all.
          The boot has a bit of volume, but it can easily be managed with the lacing, thanks to the malleable tongue area—Scarpa describes this as "Sockfit." I found the heel cup to be a bit big prior to lacing, and it gave me a feeling I often get with Scrapas: tighter around the ankle, but with a little space behind the heel. Like the volume, however, this doesn't seem to be an issue after lacing. The heel cup actually proved to be nice when walking down ice and snow (more on that later).
          On my first outing in the Ribelle HDs, a hike, I found they walked really well. I still wasn't completely used to the balance points and the sole seemed to have a lightweight bulk to it, which was really just an optical illusion. If you haven't ever tried a crossover style boot, it can be hard to explain, but I found that the Ribelle HDs seem to have more rubber around the foot, and I felt like I lost some sensitivity that I'm used to in a mountain boot with a sleeker sole, like a Trango or Charmoz. Once I trusted the HDs more, I actually found them to give me better footing on scree slopes.
          That first outing wasn't a spectacular hike, but it was longer than anything I had done all season and I was fully expecting to feel an achy soreness from my left foot (the one with the metal pins inside it.) Surprisingly, my foot did not feel sore.
          My second trip with the Ribelle HDs involved a much longer slog up to Mt. Hector, a glaciated snow and ice peak in the Canadian Rockies. Once again, I felt pretty balanced in third-class sub-alpine trails through the talus. In fourth-class terrain, I was still a bit hesitant to completely trust the rockered sole. Once on ice, the HDs felt stiff and coupled well with the Petzl Irvis crampons. The snow was pretty bad, so I hit a few holes. I didn't wear gaiters, so eventually my feet were wet. The Ribelle HDs are super warm, but not as waterproof as I would like. We got hit with rain on the way down and when I reached my cache of dry approach shoes, I promptly swapped. Again, my feet didn't feel tired. Other parts of my body did, but that problem foot felt OK.
          
          The boots were wet the next day, partly because I didn't set them out to dry and partly because they aren't the most waterproof boots. I did find them to dry fairly quickly with my body heat after wearing them for a short time. Again, they molded even more around my foot. That is the beauty of a leather boot.
          The paradox of the Ribelle HD is that in some ways it is this super modern spaceship-looking boot, and in other ways it is just a classic leather boot. I really like it. Do I wish Scarpa would make smaller sizes in their premier boots, such as the Phantom Tech or Ribelle HD? Yes, yes I do (wink, wink, nudge, nudge). But for now, those with smaller feet can keep up with boots like the HD.
          Kate Erwin has been very picky about footwear since before she started climbing in high school. She took a bit of a hiatus to work in the fashion world, then motorsports, but decided that being cold and swinging axes in the Canadian Rockies is more fun than fast cars, and that technical gear is much more useful than stylish duds.
          `
        },
        {
          id: 9,
          name: 'Blue Snapback',
          imageUrl: 'https://i.ibb.co/Dpmx8qQ/trango-vergo-2.jpg',
          summary:`There being little chalk to guide the way, I backed off a misread path toward the fifth bolt, and as I stepped down to a rounded knob of micro-conglomerate, Pop! I was floating in air. Instinctively, I reached for the rope and immediately felt a burn on the inside of my fingers as they slid down the cord. In that moment, this is what crossed my mind: "Relax, the Vergo will catch you." I took my own advice, relaxed, let go and gave into the fall. After coming to a stop 30 feet above the ledge, I looked down and saw that my belayer had been hit by the flying baseball-sized chunk. She was crouched down and checking herself for damage. Though she kept her hand on the brake, I must say that I was glad the Trango Vergo was the belay device of choice that day.
          ...`,
          title: `The Trango Vergo: Assisted braking made easier for belays`,
          text:`There being little chalk to guide the way, I backed off a misread path toward the fifth bolt, and as I stepped down to a rounded knob of micro-conglomerate, Pop! I was floating in air. Instinctively, I reached for the rope and immediately felt a burn on the inside of my fingers as they slid down the cord. In that moment, this is what crossed my mind: "Relax, the Vergo will catch you." I took my own advice, relaxed, let go and gave into the fall. After coming to a stop 30 feet above the ledge, I looked down and saw that my belayer had been hit by the flying baseball-sized chunk. She was crouched down and checking herself for damage. Though she kept her hand on the brake, I must say that I was glad the Trango Vergo was the belay device of choice that day.
          There being little chalk to guide the way, I backed off a misread path toward the fifth bolt, and as I stepped down to a rounded knob of micro-conglomerate, Pop! I was floating in air. Instinctively, I reached for the rope and immediately felt a burn on the inside of my fingers as they slid down the cord. In that moment, this is what crossed my mind: "Relax, the Vergo will catch you." I took my own advice, relaxed, let go and gave into the fall. After coming to a stop 30 feet above the ledge, I looked down and saw that my belayer had been hit by the flying baseball-sized chunk. She was crouched down and checking herself for damage. Though she kept her hand on the brake, I must say that I was glad the Trango Vergo was the belay device of choice that day.Having been a die-hard fan of the Petzl Grigri for more than 20 years, I now proclaim that after less than three months of using the Trango Vergo assisted braking belay and rappel device, I am officially a Vergo convert. A light sadness trickles through my body in making this bold statement. Grigris (and wonderful belayers) have caught thousands of my falls, large and small, and kept me from hitting the ground; the Grigri has been right there with me at some of my finest and most memorable moments. Yet here I stand (or sit in front a computer) and type this pronouncement.
          My assigned duty as an Alpinist Mountain Standards reviewer is not to sell items, but rather to give assessments that are as objective as possible. With that said, even though I am not here to sell the Vergo over the Grigri or any other belay device, I want the reader to know that the five stars I am giving this device do not come purely from an intellectually clinical perspective—there's some real juice behind these words. Selling point numero uno, dos, tres y cuatro, para mi, all come down to this single function of the Vergo: when it clinches onto a rope, it really clinches; and I truly cannot emphasize "really clinches" enough.
          To provide a little background, an assisted braking device refers to a belay and rappel device that, without any, or with little effort provided by the brake hand, pinches the rope and stops it from moving farther. For reference, the Black Diamond ATC is the standard non-assisted belay device and requires an active brake hand holding the brake end of the rope to create enough friction to catch a falling climber. The Petzl Grigri, on the other hand, is the standard assisted braking device, so much so that at my local climbing gym there are multiple posters on the walls showing how to load and use the Grigri—just the Grigri, not other devices. In most situations, should the brake hand happen not to be holding the brake end of the rope at the moment when a climber falls, the Grigri will catch the climber on its own (though of course handless use is against the manufacturer's recommendations).
          Since the Grigri has set the standard for assisted braking tools for more than two decades, this review will focus on the pros and cons of the Vergo often in comparison to the Grigri. For the record, a short list of other comparable mechanically assisted braking devices includes the Wild Country Revo and the Beal Birdie.
          As mentioned already, when the Vergo cinches, it really cinches. This is 90% pro and 10% con. Until you feel it in your hands while belaying, you won't truly be able to appreciate the sense of security the Vergo offers. When I pull in slack while toprope belaying my partner, or when catching her when she falls, it's similar to the feeling of a really good hand jam, a sinker jug at the end of a pumpy crux, or a 3.5-inch cam placed deep into a splitter crack in varnished sandstone. Bam. No question, this puppy ain't going nowhere. When I'm lowering my lightweight 8-year-old son on a toprope climb using thin ropes and with lots of friction at the anchor, the Grigri often doesn't completely catch—the rope slowly slides through the device because there isn't enough weight to engage the cam. Same scenario, the Vergo easily holds tight. Whether catching lead falls during an accidental hands-free moment, holding tight on a fixed line while equipping a new route, or being used by a new belayer with sloppy brake-hand work—the Vergo's right there tight on the rope. I'll get to the 10% con in a bit.
          There being no perfect device, I quickly found the one major downside to the Vergo. Where the Grigri can belay like an ATC because of its need for a certain amount of force to engage the pinching mechanism on the rope—and this also being one of the downfalls to the Grigri because of its tendency to slip or come unlocked (unassisted) without said force—the Vergo has its equally prevalent dark side. With unrivaled clinching comes equally unrivaled difficulty in releasing the clinch—the 10% con. When the lead belayer short-ropes the leader by not giving enough slack—and the rope comes tight on the leader while they are trying to make upward progress or attempting to clip into protection—the Vergo can be a bit challenging to release and get that much-needed slack to the leader. Pulling on the lowering lever would appear to be an obvious solution, but in reality this method is awkward and time-consuming, as it requires the movement of the brake hand from the lead-belay position to the lowering position. Not fun and it can reduce safety. In the heat of the moment this is like trying to turn quickly left in an intersection to avoid a car accident while one hand is holding a donut and the other a topless cup of coffee. The best solution to the problem I could find, which was confirmed by a Trango rep, is to bump the palm of the hand down firmly on top of the Vergo. With enough force this method works very quickly, though the leader might feel a slight tug—also not fun.
          The other two downsides of the Vergo are tiny and hardly worth mentioning. Occasionally the lever stays upright after lowering the climber because the back end of the lever temporarily gets caught behind the hole where the carabiner goes. This flaw does not impact safety as far as I can tell; the lever only sticks for a moment and then falls back into place on its own. Number two: the Vergo weighs 195 grams (6.9 oz.), the Grigri weighs 175 grams (6.2 oz.) and the Grigri+ comes in at 200 grams (7.1 oz.). We're not talking a big weight difference here, but I was surprised that the Vergo weighed more than the standard Grigri, though less than an ounce. The Vergo's tighter, lower profile (which rests nicely against the body when climbing) made it seem lighter than the Grigri to me.
          `
        },{
          id:10,
          imageUrl:'https://i.ibb.co/y4f8RtS/banff-book-comp-2020.jpg',
          summary:`The Banff Mountain Book Competition released the long list of contenders for various categories on September 15—two stories from Alpinist magazine are being considered for Best Mountaineering Article: "Denali, A Universe," by Jan Harper-Haines, first published in Alpinist 67 (Autumn 2019), and "Melting Giants," by Benjamin Ribeyre and Erin Smart, Alpinist 68 (Winter 2019-20)...`,
          title:`Two Alpinist stories are candidates for Best Mountaineering Article in the Banff Mountain Book Competition`,
          text:`The Banff Mountain Book Competition released the long list of contenders for various categories on September 15—two stories from Alpinist magazine are being considered for Best Mountaineering Article: "Denali, A Universe," by Jan Harper-Haines, first published in Alpinist 67 (Autumn 2019), and "Melting Giants," by Benjamin Ribeyre and Erin Smart, Alpinist 68 (Winter 2019-20). "Leper Chai," by Jeff Long for Rock and Ice is also nominated.
          Additionally, two books by recent Alpinist contributors Bernadette McDonald and David Smart are on the list for Non-Fiction Mountain Literature, respectively: Winter 8000: Climbing the World's Highest Mountains in the Coldest Season, and Emilio Comici: Angel of the Dolomites. Related articles to those books were recently published in Alpinist 70—"Nanga Parbat: The Magnificent Obsession" by McDonald—and "Blood That Dreams of Stone: Antonia Pozzi, Climbing Poet," by Smart in Alpinist 68. Other past Alpinist contributors are also being recognized at Banff.
          This year's jury panelists are Helen Rolfe, Nandini Purandare and Pete Takeda.
          "Melting Giants" will soon be available in audio format in Season 2 of Alpinist Aloud, a podcast in which selected stories from the print magazine are read out loud. You can find Season 1 of Alpinist Aloud and other episodes of the Alpinist Podcast here.
          The Banff Centre website describes the book competition as "an internationally recognized literary competition that celebrates mountain literature in all its forms. Over $20,000 in cash is awarded annually with eight awards selected by an international jury of writers, adventurers and editors. The short list of category award winners eligible for the Grand Prize is announced in October every year. In 2020, the Grand Prize will be announced on Thursday, November 5, at the Festival and category awards will be presented to winning authors."
          `
        }
       
      ]
}
export default DATA;
// https://i.ibb.co/M9bDrZ6/Article-Image-Handler.png
// https://i.ibb.co/qWxKTyM/Article-Image-Handler-1.jpg
// https://i.ibb.co/y4f8RtS/banff-book-comp-2020.jpg
// https://i.ibb.co/4VSpHJj/grand-teton-north-buttress-direct-1.jpg
// https://i.ibb.co/Gc2bNkF/grand-teton-north-buttress-direct-6.jpg
// https://i.ibb.co/s1HhQhR/k2-abruzzi-spur-wiki-photo-bw.jpg

// 


